#!/usr/bin/env python3
"""
Generate wikiart_index.js by scanning the wikiart/ directory.

Run from the docs/ directory:
    python3 generate_wikiart_index.py

Options:
    --max N     Limit to N images per genre (random sample). Default: all.
    --out FILE  Output filename. Default: wikiart_index.js
"""

import os
import json
import random
import argparse

WIKIART_DIR = "wikiart"
OUTPUT_FILE = "wikiart_index.js"
IMAGE_EXTS  = {".jpg", ".jpeg", ".png", ".webp"}


def main():
    parser = argparse.ArgumentParser(description="Generate wikiart_index.js")
    parser.add_argument("--max", type=int, default=None, metavar="N",
                        help="Max images per genre (random sample). Default: all.")
    parser.add_argument("--out", default=OUTPUT_FILE, metavar="FILE",
                        help="Output filename. Default: wikiart_index.js")
    args = parser.parse_args()

    if not os.path.isdir(WIKIART_DIR):
        print(f"Error: '{WIKIART_DIR}' directory not found. "
              "Run this script from the docs/ directory.")
        raise SystemExit(1)

    all_paths = []
    genre_counts = {}

    for genre in sorted(os.listdir(WIKIART_DIR)):
        genre_path = os.path.join(WIKIART_DIR, genre)
        if not os.path.isdir(genre_path):
            continue

        images = [
            f"wikiart/{genre}/{fname}"
            for fname in sorted(os.listdir(genre_path))
            if os.path.splitext(fname)[1].lower() in IMAGE_EXTS
        ]

        if args.max and len(images) > args.max:
            images = random.sample(images, args.max)

        genre_counts[genre] = len(images)
        all_paths.extend(images)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_wikiart_index.py\n")
        f.write("// Run `python3 generate_wikiart_index.py` from docs/ to regenerate.\n")
        f.write("// Optional: --max N to limit images per genre, --out FILE to rename output.\n")
        f.write("var WIKIART_IMAGES = ")  # var, not const — must be a window property
        f.write(json.dumps(all_paths, indent=2))
        f.write(";\n")

    total = len(all_paths)
    print(f"Wrote {total} images to {args.out}")
    for genre, count in genre_counts.items():
        print(f"  {genre}: {count}")


if __name__ == "__main__":
    main()
